" Aesthetics
syntax on
set t_Co=256
set background=dark
set title
set number
set ruler
set laststatus=2
set wildmenu
set wildmode=longest,full
set novisualbell
set noerrorbells
set ttyfast
set showcmd
set showmatch

" Configuration
filetype indent on
set encoding=utf-8
set nocompatible
set virtualedit=onemore
set backspace=indent,eol,start
set nowrap
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set ignorecase
set smartcase
set hlsearch
set noswapfile
set nobackup
set nowb
set eol
set autoindent
set copyindent
let g:netrw_liststyle=3

" Remaps
map <C-l> :let @/ = ""<CR>
