export ZSH=/Users/evan/.oh-my-zsh

ZSH_THEME="crabtr"

ENABLE_CORRECTION="true"

plugins=(git colored-man-pages)

source $ZSH/oh-my-zsh.sh

# Base16 Shell
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Ripgrep config
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc

# Go paths
export GOPATH=$HOME/Documents/code/Go
export GOBIN=$GOPATH/bin

# Custom paths for code directories
export CODE=$HOME/Documents/code
export CPPWORK=$CODE/C++
export GOWORK=$GOPATH/src/github.com/crabtr
export JAVAWORK=$CODE/Java
export JSWORK=$CODE/Javascript
export PYWORK=$CODE/Python
export RUSTWORK=$CODE/Rust

export PATH="$PATH:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/mysql/bin:$GOPATH:/Users/evan/.cargo/bin"

alias ll="ls -alh"
alias glog="git log --graph --decorate"
alias smerge="/Applications/Sublime\ Merge.app/Contents/SharedSupport/bin/smerge ."

# alias vim="/usr/local/Cellar/vim/8.1.0500/bin/vim"
# alias gcc="/usr/local/Cellar/gcc/7.3.0/bin/gcc-7"

# It's ridiculous I have to do this
# alias load_ssl="export OPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2p/include && export OPENSSL_LIB_DIR=/usr/local/Cellar/openssl/1.0.2p/lib"

alias resize_twitch="osascript -e 'tell application \"Firefox\" to set the bounds of front window to {-1710, 22, 0, 1080}'"
alias resize_youtube="osascript -e 'tell application \"Firefox\" to set the bounds of front window to {-1676, 22, 0, 1080}'"
alias resize_netflix="osascript -e 'tell application \"Firefox\" to set the bounds of front window to {268, 97, 1634, 947}'"
alias resize_vlc="osascript -e 'tell application \"VLC\" to set bounds of front window to {-1600, 22, -320, 800}'"

# Convert markdown to html
# function md2html {
#     if [ -z "$2" ]; then
#         markdown $1 > "$(echo $1 | cut -f 1 -d '.').html"
#     else
#         markdown $1 > $2
#     fi
# }

# Format JSON data
function format_json {
    python3 -m json.tool $1 > /tmp/tmpdata.json
    rm $1
    cat /tmp/tmpdata.json > $1
    rm /tmp/tmpdata.json
}

# Length of a given string
# Usage: strlen "string in quotes"
function strlen() {
    temp=$1; echo "${#temp}"
}
